version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    env_file:
      - .env

  client:
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - server